#!/usr/bin/env python3
"""Generate one atlas organ per Bonfyre command from REAL disk state.

Every cmd/Bonfyre* becomes a first-class architecture -- source_path to its real
sources, honest maturity from real evidence (measured if it ships a selftest/tests,
implemented if it is built and responds to --help, declared if source-only), the
capability it realizes, and the smoke harness as a runtime witness. No fabrication:
every field is grounded in files on disk and the command_smoke.json record.

Writes architecture/commands/command-surface.yaff. Re-run after building commands.
"""

from __future__ import annotations

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
CMD = os.path.join(REPO, "cmd")
OUT = os.path.join(HERE, "commands", "command-surface.yaff")

# capability / Bonfyre fact each well-known command realizes (curated); the rest
# realize a capability named for themselves. Mirrors command_advertisements.py.
CAPABILITY = {
    "BonfyreAuth": ("Authority", "Authority / Access"),
    "BonfyreGate": ("Authority", "Authority / Gate"),
    "BonfyreCapability": ("Capability", "Capability / Inventory"),
    "BonfyreDiscipl": ("Capability", "Capability / Composition"),
    "BonfyreLearn": ("Capability", "Capability / Acquisition"),
    "BonfyreLedger": ("Value", "Economic / Ledger"),
    "BonfyreFinance": ("Value", "Economic / Finance"),
    "BonfyreEconomy": ("Value", "Economic / Economy"),
    "BonfyreFPQ": ("FPQRepresentation", "Model / FPQ"),
    "BonfyreFPQx": ("FPQRepresentation", "Model / FPQ"),
    "BonfyreKVCache": ("KVPassport", "Model / KV"),
    "BonfyreGraph": ("Relation", "Identity / Graph"),
    "BonfyreEntity": ("Actor", "Identity / Entity"),
    "BonfyreHash": ("Artifact", "Identity / Content"),
    "BonfyreFS": ("NamespaceProjection", "Fabric / Namespace"),
    "BonfyreEmbed": ("SID", "Model / Embedding"),
    "BonfyreVec": ("SID", "Model / Vector"),
    "BonfyreIndex": ("AddressAdvertisement", "Forwarding / Index"),
    "BonfyreProof": ("ProofFrontier", "Evidence / Proof"),
    "BonfyreInfer": ("ExecutionReceipt", "Model / Inference"),
    "BonfyreGen": ("ExecutionReceipt", "Model / Generation"),
    "BonfyreCMS": ("Publication", "Surface / CMS"),
    "BonfyreQueue": ("WorkState", "Execution / Queue"),
    "BonfyreProject": ("WorkState", "Execution / Project"),
    "BonfyreEmit": ("Occurrence", "Execution / Emit"),
    "BonfyreIngest": ("ExternalEvent", "Execution / Ingest"),
    "BonfyreCompress": ("Representation", "Model / Compression"),
}
_MUTATING = ("Auth", "Gate", "Ledger", "Finance", "Emit", "Ingest", "Queue",
             "Project", "CMS", "Distribute", "Sync", "Pipeline", "Publish")


def _sources(cmd_dir: str, name: str) -> list[str]:
    out = []
    for root in (os.path.join(cmd_dir, "src"), cmd_dir):
        if not os.path.isdir(root):
            continue
        for f in sorted(os.listdir(root)):
            if f.endswith((".c", ".h", ".rs", ".zig", ".cpp", ".cc", ".go")):
                rel = os.path.relpath(os.path.join(root, f), REPO)
                out.append(rel)
        if out:
            break
    return out[:4]


def _slug(name: str) -> str:
    return "cmd-" + re.sub(r"(?<!^)(?=[A-Z])", "-", name[len("Bonfyre"):]).lower()


def generate() -> str:
    smoke = {}
    sp = os.path.join(CMD, "command_smoke.json")
    if os.path.exists(sp):
        for r in json.load(open(sp)).get("results", []):
            smoke[r["command"]] = r

    EXCLUDE = {"BonfyreFS"}  # already a first-class fabric organ (bonfyre-fs)
    names = sorted(n for n in os.listdir(CMD)
                   if os.path.isdir(os.path.join(CMD, n)) and n.startswith("Bonfyre") and n not in EXCLUDE)
    lines = ["atlas command",
             "# Generated by generate_command_organs.py from real disk state -- one",
             "# organ per Bonfyre command. Do not hand-edit; re-run after building.",
             "# maturity: measured (ships selftest/tests), implemented (built + responds",
             "# to --help), declared (source-only). source_path is real; witness is the",
             "# smoke harness for live commands.", ""]
    for name in names:
        d = os.path.join(CMD, name)
        cap, domain = CAPABILITY.get(name, (name.replace("Bonfyre", "") + "Capability",
                                            "Command / " + name.replace("Bonfyre", "")))
        srcs = _sources(d, name)
        r = smoke.get(name, {})
        live = r.get("responds", False)
        has_test = os.path.isdir(os.path.join(d, "tests")) or bool(
            [f for f in os.listdir(d) if "selftest" in f.lower()]) if os.path.isdir(d) else False
        if live and has_test:
            maturity = "measured"
        elif live:
            maturity = "implemented"
        elif srcs:
            maturity = "declared"
        else:
            maturity = "architectural"
        mutating = any(m in name for m in _MUTATING)
        lines.append(f"architecture {_slug(name)}")
        lines.append(f"  canonical_name {name}")
        lines.append("  family command")
        lines.append(f"  domain {domain}")
        lines.append(f"  semantic_question What does the {name} capability organ realize, and by what contract?")
        lines.append(f"  purpose Command-surface organ realizing the {cap} capability. "
                     f"A first-class Bonfyre capability, advertised and composable, not a script.")
        lines.append(f"  maturity {maturity}")
        lines.append(f"  command {name}")
        CONSUMED_FACTS = {"Authority","Value","WorkState","Occurrence","ExternalEvent",
                         "ExecutionReceipt","Actor","Relation","Artifact","ProofFrontier",
                         "FPQRepresentation","KVPassport","Capability"}
        if name in CAPABILITY and cap in CONSUMED_FACTS:
            lines.append(f"  publishes {cap}")
        lines.append(f"  internal_calculus {r.get('binary', name)} binary")
        lines.append(f"  forbidden_inference the command exists -> its effect is authorized "
                     f"({'Authority gates the commit' if mutating else 'read-only, but scope still applies'})")
        for s in srcs:
            lines.append(f"  source_path {s}")
        if live:
            lines.append("  witness cmd/command_smoke.py")
        lines.append("  source_lineage the 91-command capability surface")
        note = ("responds to --help (live)" if live else
                ("source-only, not built" if srcs else "declared, no source found"))
        lines.append(f"  known_gap {note}; realizes {cap}; deeper development toward the "
                     f"BonfyreFS level (WiringSpec consumes/produces, full contract) is ongoing")
        lines.append("")
    open(OUT, "w").write("\n".join(lines) + "\n")
    return OUT


if __name__ == "__main__":
    path = generate()
    n = open(path).read().count("architecture cmd-")
    print(f"wrote {path}: {n} command organs")
