import { createHash } from 'node:crypto';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { join } from 'node:path';

export const GENERATION_SCHEMA = 'bonfyre.native.generation.result.v1';
export const GENERATION_CONTENT_TYPE = 'cms_generation';

function text(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function integer(value, fallback) {
  return Number.isInteger(value) && value > 0 ? value : fallback;
}

function run(binary, args, options, spawnImpl, timeoutMs = 120_000) {
  return new Promise((resolve, reject) => {
    const child = spawnImpl(binary, args, options);
    let stderr = '';
    let stdout = '';
    let settled = false;
    const timer = setTimeout(() => {
      if (settled) return;
      child.kill('SIGKILL');
      settled = true;
      resolve({ code: null, signal: 'SIGKILL', stderr, stdout, timed_out: true });
    }, timeoutMs);
    child.stdout?.on('data', (chunk) => { stdout += chunk.toString(); });
    child.stderr?.on('data', (chunk) => { stderr += chunk.toString(); });
    child.once('error', (error) => { if (!settled) { settled = true; clearTimeout(timer); reject(error); } });
    child.once('close', (code, signal) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({ code, signal, stderr, stdout, timed_out: false });
    });
  });
}

export function toGenerationCmsEntry(result, { namespace = 'bonfyre-generation' } = {}) {
  if (!result || result.schema_version !== GENERATION_SCHEMA) {
    throw new Error('A native generation result is required');
  }
  const output = typeof result.output === 'string' ? result.output : '';
  const digest = text(result.output_sha256);
  if (!output || !digest) throw new Error('Generation result is missing output identity');
  if (!text(namespace)) throw new Error('namespace is required');
  const model = text(result.model?.name || result.model?.binary || 'bonfyre-native');
  return {
    schema_version: 'bonfyre.native.cms.entry.v1',
    content_type: GENERATION_CONTENT_TYPE,
    namespace,
    external_id: `${model}:${digest}`,
    idempotency_key: `${GENERATION_SCHEMA}:${digest}`,
    fields: {
      title: `Generated by ${model}`,
      status: 'generated',
      output,
      output_sha256: digest,
      model,
      backend: text(result.backend || 'cpu_neon'),
      prompt_sha256: text(result.prompt_sha256),
      max_new_tokens: String(result.request?.max_new_tokens || ''),
      source_event: 'native.generate',
      source_schema_version: GENERATION_SCHEMA,
      source_received_at: text(result.generated_at),
    },
    source_event: 'native.generate',
    received_at: result.generated_at,
  };
}

export function createNativeGenerationClient({
  binary,
  modelPack,
  tokenizer,
  spawnImpl = spawn,
  tempRoot = '/tmp',
} = {}) {
  if (!text(binary) || !text(modelPack) || !text(tokenizer)) {
    throw new Error('binary, modelPack, and tokenizer are required');
  }
  if (typeof spawnImpl !== 'function') throw new Error('spawnImpl is required');

  async function generate({ prompt, maxNewTokens = 20, greedy = true, env = {}, timeoutMs = 120_000 } = {}) {
    const sourcePrompt = typeof prompt === 'string' ? prompt : '';
    if (!sourcePrompt) throw new Error('prompt is required');
    const limit = integer(maxNewTokens, 20);
    const tempDir = await mkdtemp(join(tempRoot, 'bonfyre-generation-'));
    const promptPath = join(tempDir, 'prompt.txt');
    const outputPath = join(tempDir, 'output.txt');
    const started = Date.now();
    try {
      await writeFile(promptPath, sourcePrompt, 'utf8');
      const args = [
        'generate', '--pack', modelPack, '--tokenizer', tokenizer,
        '--prompt', promptPath, '--out', outputPath,
        ...(greedy ? ['--greedy'] : []), '--max-new-tokens', String(limit),
      ];
      const execution = await run(binary, args, {
        env: { ...process.env, ...env },
        cwd: process.cwd(),
      }, spawnImpl, timeoutMs);
      if (execution.timed_out) throw new Error(`Native generation timed out after ${timeoutMs}ms`);
      if (execution.code !== 0) {
        throw new Error(`Native generation failed (${execution.code ?? execution.signal}): ${execution.stderr.trim()}`);
      }
      const output = await readFile(outputPath, 'utf8');
      if (output.length === 0) throw new Error('Native generation returned empty output');
      const outputSha = createHash('sha256').update(output).digest('hex');
      const promptSha = createHash('sha256').update(sourcePrompt).digest('hex');
      return {
        schema_version: GENERATION_SCHEMA,
        generated_at: new Date().toISOString(),
        model: { name: 'bonfyre-qwen-fpq', binary, pack: modelPack, tokenizer },
        backend: 'cpu_neon',
        request: { prompt: sourcePrompt, max_new_tokens: limit, greedy },
        prompt_sha256: promptSha,
        output,
        output_sha256: outputSha,
        stderr: execution.stderr,
        stdout: execution.stdout,
        elapsed_ms: Date.now() - started,
      };
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  }

  return { generate };
}
