export {
  CONTINUITY_CORE_VERSION,
  archiveStateObject,
  createAttachmentArtifact,
  createStateSnapshot,
  createStateTransition,
  createTrajectoryProjection,
  evaluateFunctionalClaims,
  forkStateObject,
  ingestKernelBatch,
  ingestKernelIntegration,
  listKernelTargets,
  mergeStateObjects,
  mutateStateObject,
  reopenStateObject,
  runKernelIntegration,
  runKernelStateMachineBatch,
  runKernelSurfaceBatch,
  stateRuntime,
} from "@aurekai/continuity-core";
